FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /app
COPY ./DrugRegistry.API . 
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
COPY wait-for-it.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-it.sh
RUN dotnet restore
CMD ["wait-for-it.sh", "db:5432", "--", "dotnet", "ef", "database", "update"]
