version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: s3cretP@ss
      POSTGRES_DB: drugdb
    restart: always  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.Migrations
    environment:
       - ConnectionStrings__Database=Host=db;Port=5432;Database=drugdb;Username=pgadmin;Password=s3cretP@ss
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
       - ConnectionStrings__Database=Host=db;Port=5432;Database=drugdb;Username=pgadmin;Password=s3cretP@ss
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
